import pandas as pd
import re
import os

configfile: "config/config.yaml"

# Sample metadata
sample_metadata_df = pd.read_excel(config['sample_metadata'], header=0)

sampleIDs = sample_metadata_df['Sample_ID'].tolist()

# PBMC scrnaseq files
scrnaseq_files_df = pd.read_excel(config['scrnaseq_files'], header=0)

scrnaseq_fastq_basenames = pd.Series(pd.concat([scrnaseq_files_df['Basename_fastq'], scrnaseq_files_df['Basename_fbc_fastq']]), name = 'files')
scrnaseq_fastq_basenames = scrnaseq_fastq_basenames[scrnaseq_fastq_basenames.notna()]

scrnaseq_fastq_df = pd.concat({'old_path' : scrnaseq_fastq_basenames,
                               'file' : scrnaseq_fastq_basenames.apply(lambda x: os.path.basename(x))},
                              axis=1)

scrnaseq_fastq_df = scrnaseq_fastq_df.drop_duplicates()
scrnaseq_fastq_fns = scrnaseq_fastq_df['file'].tolist()

run_fbcs = pd.Series(scrnaseq_files_df['Run_ID'].unique()).tolist()

scrnaseq_files_df['Well10X_str'] = scrnaseq_files_df['Well10X'].astype(str)

lookup_fbc = pd.DataFrame(list(zip(scrnaseq_files_df['Run_ID'],
                                   scrnaseq_files_df[['Run_ID', 'Well10X_str']].agg('-'.join, axis=1))),
                          columns = ['Run', 'Run_well']).drop_duplicates()

# CD14+ monocyte brnaseq files
brnaseq_files_df = pd.read_excel(config['brnaseq_files'], header=0)

brnaseq_fastq_df = pd.concat([pd.Series(pd.concat([brnaseq_files_df['Basename'].astype(str) + '_R1', brnaseq_files_df['Basename'].astype(str) + '_R2', brnaseq_files_df['Basename'].astype(str) + '_UMI']), name = 'old_path'), 
                              pd.Series(pd.concat([brnaseq_files_df['Sample_ID'].astype(str) + '_R1', brnaseq_files_df['Sample_ID'].astype(str) + '_R2', brnaseq_files_df['Sample_ID'].astype(str) + '_UMI']), name = 'file')], 
                             axis=1)

brnaseq_fastq_df = brnaseq_fastq_df.drop_duplicates()
brnaseq_fastq_fns = brnaseq_fastq_df['file'].tolist()
brnaseq_sampleIDs = brnaseq_files_df['Sample_ID'].tolist()

#print(brnaseq_fastq_df)
#print(brnaseq_fastq_fns)
#print(brnaseq_fastq_df['old_path'].tolist())

basedir = config['base_dir']

# Rules
include: "rules/pbmc_scrnaseq.smk"
include: "rules/pbmc_masscytometry.smk"
include: "rules/pbmc_flowcytometry.smk"
include: "rules/gse134809_scrnaseq.smk"
include: "rules/cd14monocyte_brnaseq.smk"
include: "rules/figures.smk"

wildcard_constraints:
  scrnaseq_fastq_fn='|'.join([re.escape(x) for x in scrnaseq_fastq_fns]),
  run_fbc='|'.join([re.escape(x) for x in run_fbcs]),
  brnaseq_fastq_fn='|'.join([re.escape(x) for x in brnaseq_fastq_fns]),
  brnaseq_sampleID='|'.join([re.escape(x) for x in brnaseq_sampleIDs]),

rule all:
  input:
    ## scRNAseq
    #expand("resources/scrnaseq/fastq/{scrnaseq_fastq_fn}", scrnaseq_fastq_fn=scrnaseq_fastq_fns),
    #"resources/scrnaseq/reference_genome",
    #expand("output/scrnaseq/cellranger/{run_fbc}/outs/filtered_feature_bc_matrix", run_fbc=run_fbcs),
    expand("{basedir}/output/scrnaseq/cellranger/{run_fbc}", basedir=basedir, run_fbc=run_fbcs),
    #expand("{basedir}/output/scrnaseq/normalized/{run_fbc}_normalized_SeuratObject.Rds", basedir=basedir, run_fbc=run_fbcs),
    #expand("{basedir}/output/scrnaseq/cell_metadata/annotated_SeuratObject.Rds", basedir=basedir),
    #expand("{basedir}/output/scrnaseq/clustered/clustered_SeuratObject.Rds", basedir=basedir),
    expand("{basedir}/output/scrnaseq/da/dacs.csv", basedir=basedir),
    expand("{basedir}/output/scrnaseq/de/pb_mds.Rds", basedir=basedir),
    #expand("{basedir}/output/scrnaseq/de/degs_{level}_list.Rds", basedir=basedir, level = ["manual_l0", "manual_l1", "manual_l2", "manual_l3"]),
    expand("{basedir}/output/scrnaseq/de/fgsea_{level}_list.Rds", basedir=basedir, level = ["manual_l0", "manual_l1", "manual_l2", "manual_l3"]),
    expand("{basedir}/output/scrnaseq/monocyte/monocyte_SeuratObject.Rds", basedir=basedir),
    ## GSE134809
    #expand("{basedir}/output/gse134809/annotated/gse134809_annotated_SeuratObject.Rds", basedir=basedir),
    expand("{basedir}/output/gse134809/da/dacs_involvedvuninvolved_immune_l3rl1.csv", basedir=basedir),
    expand("{basedir}/output/gse134809/de/degs_manual_l3_list.Rds", basedir=basedir),
    ## Mass cytometry
    expand("{basedir}/output/masscytometry/da/dacs.csv", basedir=basedir),
    #expand("{basedir}/output/masscytometry/cell_metadata/sce_annotated.Rds", basedir=basedir),
    expand("{basedir}/output/masscytometry/dimred/sce_dimred_ss.Rds", basedir=basedir),
    ## Flow cytometry
    #expand("{basedir}/output/flowcytometry/celltype_percentages.csv", basedir=basedir),
    expand("{basedir}/output/flowcytometry/da/dacs.csv", basedir=basedir),
    ## CD14+ monocyte bulk RNAseq
    #expand("resources/brnaseq/fastq/{brnaseq_fastq_fn}.fastq.gz", brnaseq_fastq_fn=brnaseq_fastq_fns),
    #"resources/brnaseq/reference_genome",
    #expand("output/fastqc/{brnaseq_fastq_fn}", brnaseq_fastq_fn=brnaseq_fastq_fns),
    #expand("resources/brnaseq/fastq_umi/{brnaseq_sampleID}_umi_R1.fastq.gz", brnaseq_sampleID=brnaseq_sampleIDs),
    #expand("output/brnaseq/bam/{brnaseq_sampleID}/{brnaseq_sampleID}_pe_Aligned.sortedByCoord.out.bam", brnaseq_sampleID=brnaseq_sampleIDs),
    #expand("output/brnaseq/bam/{brnaseq_sampleID}/{brnaseq_sampleID}_filtered.bam", brnaseq_sampleID=brnaseq_sampleIDs),
    #expand("output/brnaseq/bam/{brnaseq_sampleID}/{brnaseq_sampleID}_filtered.bam.bai", brnaseq_sampleID=brnaseq_sampleIDs),
    #expand("output/brnaseq/bam/{brnaseq_sampleID}/{brnaseq_sampleID}_filtered_deduplicated.bam", brnaseq_sampleID=brnaseq_sampleIDs),
    #"output/brnaseq/bam/STAR.log",
    #"output/brnaseq/counts/counts.txt",
    #"output/brnaseq/multiqc",
    #expand("{basedir}/output/brnaseq", basedir=basedir),
    #expand("{basedir}/output/brnaseq/counts/counts_cleaned_se.rds", basedir=basedir),
    expand("{basedir}/output/brnaseq/de/degs_rvnr.csv", basedir=basedir),
    ## Figures
    ### Fig2
    # expand("{basedir}/output/figures/scrnaseq_umap_pbmc.pdf", basedir=basedir),
    # expand("{basedir}/output/figures/scrnaseq_dotplot_markers_l3.pdf", basedir=basedir),
    # expand("{basedir}/output/figures/masscytometry_umap_pbmc.pdf", basedir=basedir),
    # expand("{basedir}/output/figures/masscytometry_heatmap_markers_l3.pdf", basedir=basedir),
    # expand("{basedir}/output/figures/scrnaseq_masscytometry_scatterplot_abundance_l3rl0_colmanuall1.pdf", basedir=basedir),
    # expand("{basedir}/output/figures/scrnaseq_umap_pbmc_ITGA4_ITGB7.pdf", basedir=basedir),
    # expand("{basedir}/output/figures/masscytometry_umap_pbmc_ITGA4_A4B7.pdf", basedir=basedir),
    expand("{basedir}/output/figures/fig2.pdf", basedir=basedir),
    ### Fig3
    # expand("{basedir}/output/figures/scrnaseq_boxplot_abundance_l3rl0.pdf", basedir=basedir),
    # expand("{basedir}/output/figures/massytometry_boxplot_abundance_l3rl0.pdf", basedir=basedir),
    expand("{basedir}/output/figures/fig3.pdf", basedir=basedir),
    ### Fig4
    # expand("{basedir}/output/figures/scrnaseq_arrowplot_degs.pdf", basedir=basedir),
    # expand("{basedir}/output/figures/fig4.pdf", basedir=basedir),
    expand("{basedir}/output/figures/fig4.pdf", basedir=basedir),
    ### Fig5
    expand("{basedir}/output/figures/fig5.pdf", basedir=basedir),
